### PR TITLE
Move .rsync-filter and ignore .git dirs

### PR DESCRIPTION
**Pull request by balbuf**
## Summary
Background: this is the result of resolving an issue with a git deploy from a project using this scaffold.

Basically the files for one of the modules in the project were not being deployed to the Acquia server. After debugging in Travis, I found that the module files were being downloaded properly by composer and even copied into the deploy directory properly. But they were basically being ignored by git, though not by gitignore. Turns out, because this module happened to be installed from source rather than dist, the deploy script was copying over the `.git` dir for the module's repo and trying to commit and deploy that to Acquia's git deploy repo. Well when you do this, git doesn't add the files; instead it adds a "gitlink," which is essentially halfway to a submodule. Because of this, git was aware of the directory but would not add any of the files within. More information here: https://stackoverflow.com/a/4162672

This likely never arose previously because most modules are installed from dist and so there is never a `.git` dir to copy in the first place. I'm moving the `.rsync-filter` to the project root so it can be generalized and used project-wide (this issue also applies for deploying dependencies in `vendor/`). While this issue only pertains to git-based deploys, I see no reason to deploy `.git` directories with an rsync-based deploy either.

## Metadata

| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes
| Did you apply meaningful labels to the pull request? | no
| Did you perform a self review first? | yes
| Documentation reflects changes? | n/a
| `CHANGELOG` reflects changes? | n/a
| Unit/Functional tests reflect changes? | n/a
| Did you perform browser testing? | n/a
| Risk level | Low
| Relevant links | none

### CODE REVIEW

**Comment by marcaddeo** [comment]
@balbuf I'm pretty sure this needs to stay in the `web` directory in order to continue working with the `oomph-infrastructure` setup.

If I remember correctly, it's because it's selectively uploading folders from the project. So it rsyncs the web folder as it's own transfer, so if the `.rsync-filter` is above the `web` directory it wont be read by `rsync`. I _think_.

The `.git` directories certainly don't need to be deployed, you're right there. I had to solve this on RISD because there were non-dist modules coming in there as well. I believe I used `find` to find all `.git` directorys, and then deleted them as part of a build step.

That's not super ideal, so maybe you can figure out a better solution. But want to point out that this potentially breaks the flow of `oomph-infrastructure`.

**Comment by marcaddeo** [comment]
@nathandentzau do you remember if that's the case?

**Comment by balbuf** [comment]
@marcaddeo you might be right about that... not sure if it looks for `.rsync-filter` in the cwd or only within the source folders (initially thought the former, but it's probably the latter like you said)

**Comment by marcaddeo** [comment]
@balbuf I wonder if it's viable to just commit a `vendor/.rsync-filter`? And then ignore `.git` in both the `web` and `vendor` filter files?

**Comment by balbuf** [comment]
@marcaddeo yeah that's what I'm thinking (it was actually my initial thought as well but then it seemed silly to have 2 files); alternatively I think we can pass additional rsync params in the ansible task, so we could probably just pass an `--exclude=.git` argument there...not sure which would be better 🤔

**Comment by marcaddeo** [comment]
@balbuf yeah either option seems fine. I'd lean toward the `.rsync-filter` option, though, so scaffolded projects are ready to deploy using `rsync` regardless of the deployment script.

**Comment by balbuf** [comment]
Updated @marcaddeo @nathandentzau

**Pull request merged**
