### PR TITLE
Remove contrib modules

### PR DESCRIPTION
**Pull request by ben-hamelin**
## Summary

Remove some contrib modules as they may not be needed for every project. 

## Metadata

| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes
| Did you apply meaningful labels to the pull request? | yes
| Did you perform a self review first? | yes
| Documentation reflects changes? | no
| `CHANGELOG` reflects changes? | yes
| Unit/Functional tests reflect changes? | no
| Did you perform browser testing? | yes
| Risk level | Low
| Relevant links | JIRA issue, bug reports, security alerts, etc.

### CODE REVIEW

**Comment by kbeck303** [comment]
oh man, I use almost all those on every project except honeypot

**Comment by syzygy333** [comment]
yeah, these seem pretty standard

**Comment by ben-hamelin** [comment]
So coffee was throwing errors during some unit testing. It made me consider whether it makes sense to bring something like that into every project, vs what we absolutely require for development. Since it's very easy to require these on a project by project basis the thought was to minimize them here.

**Comment by syzygy333** [comment]
config_split and admin_toolbar seem pretty necessary, but I understand what you're saying

**Comment by ben-hamelin** [comment]
I can add those back in - I agree we use config_split on almost every site we build.

**Comment by kbeck303** [comment]
bill nye the science guy holding laser guns

/approved

**Pull request merged**
